### PR TITLE
feat: add Apache Tika dependency

### PR DESCRIPTION
**Pull request by okamototk**
Adding Apache Tika dependency and auto configuration.

### CODE REVIEW

**Comment by 0xThresh** [comment]
Thanks @okamototk, can you please merge the latest from `main` and make sure to increment the AppVersion in Chart.yaml to 3.6.0?

**Comment by okamototk** [comment]
@0xThresh Thanks  for comment. I already rebase to main. But from Chart.yaml:

> apiVersion: v2
 > name: open-webui
> version: 3.5.0
> appVersion: "0.3.35"

Do you mean change appVersion to 0.3.36 from 0.3.35?
I though 3.6.0 is mistaken but let me confirm.

regards,

**Comment by 0xThresh** [comment]
Good catch @okamototk, yes, I meant the `version` rather than the `appVersion`. Sorry for the mix-up. Open WebUI is currently at v0.3.35, so the `appVersion` is already correct.

**Comment by okamototk** [comment]
I see. thx:)

**Comment by okamototk** [comment]
After update version to 0.3.36, have following error:
```
$ kubectl describe pods open-webui-0
...
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  11m                  default-scheduler  Successfully assigned default/open-webui-0 to ip-10-8-8-102.ap-northeast-1.compute.internal
  Normal   Pulling    10m (x4 over 11m)    kubelet            Pulling image "ghcr.io/open-webui/open-webui:0.3.36"
  Warning  Failed     10m (x4 over 11m)    kubelet            Failed to pull image "ghcr.io/open-webui/open-webui:0.3.36": rpc error: code = NotFound desc = failed to pull and unpack image "ghcr.io/open-webui/open-webui:0.3.36": failed to resolve reference "ghcr.io/open-webui/open-webui:0.3.36": ghcr.io/open-webui/open-webui:0.3.36: not found
```

So, should we only increment version after new image release?
Latest image is 0.3.35 and shouldn't increment yet.

**Comment by okamototk** [comment]
I canceled version increment due to new image isn't uploaded yet.

**Comment by 0xThresh** [comment]
Hi @okamototk, I pushed a couple commits with the update to the `Chart.yaml` file I was looking for, packaged in the Tika chart, and updated Ollama chart version since I was already there.

Thanks so much for your contribution!

**Pull request merged**
