### PR TITLE
render env vars as yaml

### PR DESCRIPTION
**Pull request by plenti-chris-fowles**
- **render envVars as yaml (allow valueFrom)**
- **add env var example**

relates to #14 

allows use of secrets and config maps as sources for env var values (e.g. OPENAI_API_KEY as a secret)

### CODE REVIEW

**Comment by tjbck** [comment]
@0xThresh review wanted 🙌

**Comment by 0xThresh** [comment]
Thanks for the PR @plenti-chris-fowles, I'll test this out today. Note that if we approve and merge this, you'll need to bump the chart version up before it'll be deployed, so please bump the chart up a version in a new commit.

**Comment by 0xThresh** [comment]
I ran into an issue with this chart and the current version of the chart that I haven't seen before, so I'm going to have to troubleshoot that further before I can test and approve this, sorry for the delay

**Comment by 0xThresh** [comment]
@tjbck I was finally able to test this update out and it's working for me. This is the result of pulling an env var from a secret by uncommenting the example added to the `values.yaml` file:
image

LGTM!

**Comment by plenti-chris-fowles** [comment]
Hey folks,

Happy to bump the chart version myself - this is usually something that the release management team would take care of however (as I don't have control over the order in which PRs are merged).

I'll bump it now, but you may want to consider a different approach if you start getting more contributions to this repo. <3

**Comment by tjbck** [comment]
Thanks everyone!

**Pull request merged**
