### PR TITLE
Move extraEnvVars to Workload from ConfigMap

### LINKED ISSUE #86: ENABLE_OLLAMA_API being set to false if ollama.enabled is false
I don't want Ollama automatically installed but I still want to set a base URL and have the API enabled. 

A change went into the 3.1.x version of the chart that sets ENABLE_OLLAMA_API  to false if ollama.enabled is false. The commit message seems to imply the opposite though, https://github.com/open-webui/helm-charts/commit/2062a5d4e67ca27919c58875bb69579e8fa42906 but it is not setting the URL if Ollama isn't set to be automatically deployed. See this comment https://github.com/open-webui/helm-charts/blob/main/charts/open-webui/values.yaml#L4 for how enabling ollama is to deploy it vs. just to use the API.

Rolling the chart back to `3.1.18` fixes this for me. I am unable to go up to `3.2.x` because my ODIC log in stops working after the change to config maps but since this issue was introduced first (and looks to be copied into the ConfigMap change) I'll look more into that after this.

Thanks!

### LINKED ISSUE #87: ExtraEnvVars does not support secrets for Open WebUI Chart
The Open WebUI Chart places the `extraEnvVars` into a config map which doesn't allow secrets to be used though the `values.yaml` mentions otherwise.

I suppose the simplest fix would be to move the environment variables directly into the stateful set instead of config map like the pipelines chart.

### PR DESCRIPTION
**Pull request by saip92**
The `extraEnvVars` value in the open-webui chart is inserted into a config map which is later mounted in the workload (deployment/stateful set) for its environment variables. But this does not support referencing secrets which are needed when using features like OIDC Authentication or PostgreSQL as the database.

This PR removes the config map and moves the environment variables directly into the workload itself.

fixes #86
fixes #87

### CODE REVIEW

**Comment by JacopKane** [comment]
Nice!

**Comment by JacopKane** [comment]
Nice, I guess this fixes disabling the API when you disable the bundled Ollama chart.

**Comment by 0xThresh** [comment]
Hey @saip92, much appreciated on the PR - I tagged you for further discussion in #87. If we decide to merge this PR as the quick-fix, I still need you to update the `appVersion` in `Chart.yaml` so that merging this PR will trigger a new version release with these fixes added.

Thank you!

**Comment by saip92** [comment]
@0xThresh Done. I've made it a minor update like the previous change since this affects how environment variables are stored which could be a breaking change for some.

Let me know if you would like it to just be a patch release instead.

**Comment by 0xThresh** [comment]
Thanks @saip92 🫡

**Pull request merged**
