### PR TITLE
feat: bump ollama chart to 0.54

### PR DESCRIPTION
**Pull request by chr0n1x**
Bumping for https://github.com/otwld/ollama-helm/pull/89

### CODE REVIEW

**Comment by 0xThresh** [comment]
Thanks @chr0n1x , did you intend to include the update to `values.yaml`?

**Comment by chr0n1x** [comment]
@0xThresh yeah, I thought having a comment in there as a part of the example snippet would be helpful. Is that ok though? Would you like me to remove it?

**Comment by chr0n1x** [comment]
@0xThresh friendly ping - please let me know if I should change anything in this PR 😄

**Comment by 0xThresh** [comment]
Sorry @chr0n1x, it's not a big enough deal to hold this PR up over. I may edit the comment in a future release, but thank you for updating the chart!

**Pull request merged**
